name: nwf-stretch
channels:
  - conda-forge
  - defaults
dependencies:
  - networkx=2.6
  - numpy=1.19.2
  - python=3.8
  - scipy
  - pandas
  - matplotlib
  - tqdm
  - scikit-learn
  - requests
  - pot=0.7.0